name: upi_pay
description: A flutter plugin to launch UPI payment applications on Android and iOS towards making UPI payments.
version: 1.0.1

homepage: https://github.com/drenther/upi_pay

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.2
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.drenther.upi_pay
        pluginClass: UpiPayPlugin
      ios:
        pluginClass: UpiPayPlugin
  assets:
    - assets/apps/ios/
